function getRandomInt(max) {
  return math.floor(math.random() * max);
}

let intelligence = getRandomInt(100);
let power = getRandomInt(100);
let defense = getRandomInt(100);
let mobility = getRandomInt(100);
let health = getRandomInt(100);
let stealth = getRandomInt(100);

let animals = [
  {
    "Name": "Elephant",
    "Intelligence": 90,
    "Power": 95,
    "Defense": 80,
    "Mobility": 35,
    "Health": 95,
    "Stealth": 40,
    "Image": 1,
    "Id": "elephant"
  },
  {
    "Name": "Hippopotamus",
    "Intelligence": 55,
    "Power": 80,
    "Defense": 75,
    "Mobility": 65,
    "Health": 90,
    "Stealth": 60,
    "Image": 1,
    "Id": "hippopotamus"
  },
  {
    "Name": "Sturgeon",
    "Intelligence": 55,
    "Power": 70,
    "Defense": 75,
    "Mobility": 75,
    "Health": 100,
    "Stealth": 35,
    "Image": 1,
    "Id": "sturgeon"
  },
  {
    "Name": "Crocodile",
    "Intelligence": 70,
    "Power": 100,
    "Defense": 45,
    "Mobility": 50,
    "Health": 65,
    "Stealth": 80,
    "Image": 1,
    "Id": "crocodile"
  },
  {
    "Name": "Whale",
    "Intelligence": 90,
    "Power": 60,
    "Defense": 55,
    "Mobility": 65,
    "Health": 100,
    "Stealth": 40,
    "Image": 1,
    "Id": "whale"
  },
  {
    "Name": "Orca",
    "Intelligence": 90,
    "Power": 75,
    "Defense": 35,
    "Mobility": 70,
    "Health": 75,
    "Stealth": 55,
    "Image": 1,
    "Id": "orca"
  },
  {
    "Name": "Rhinoceros",
    "Intelligence": 35,
    "Power": 85,
    "Defense": 95,
    "Mobility": 65,
    "Health": 75,
    "Stealth": 40,
    "Image": 1,
    "Id": "rhinoceros"
  },
  {
    "Name": "Cattle",
    "Intelligence": 40,
    "Power": 85,
    "Defense": 75,
    "Mobility": 80,
    "Health": 80,
    "Stealth": 30,
    "Image": 1,
    "Id": "cattle"
  },
  {
    "Name": "Falcon",
    "Intelligence": 55,
    "Power": 85,
    "Defense": 35,
    "Mobility": 100,
    "Health": 40,
    "Stealth": 60,
    "Image": 1,
    "Id": "falcon"
  },
  {
    "Name": "Hyena",
    "Intelligence": 50,
    "Power": 80,
    "Defense": 45,
    "Mobility": 85,
    "Health": 60,
    "Stealth": 55,
    "Image": 1,
    "Id": "hyena"
  },
  {
    "Name": "Camel",
    "Intelligence": 52,
    "Power": 74,
    "Defense": 52,
    "Mobility": 72,
    "Health": 67,
    "Stealth": 48,
    "Image": 1,
    "Id": "camel"
  },
  {
    "Name": "Tapir",
    "Intelligence": 60,
    "Power": 65,
    "Defense": 65,
    "Mobility": 45,
    "Health": 65,
    "Stealth": 55,
    "Image": 1,
    "Id": "tapir"
  },
  {
    "Name": "Penguin",
    "Intelligence": 70,
    "Power": 50,
    "Defense": 55,
    "Mobility": 55,
    "Health": 80,
    "Stealth": 40,
    "Image": 1,
    "Id": "penguin"
  },
  {
    "Name": "Wombat",
    "Intelligence": 50,
    "Power": 70,
    "Defense": 45,
    "Mobility": 60,
    "Health": 60,
    "Stealth": 65,
    "Image": 1,
    "Id": "wombat"
  },
  {
    "Name": "Octopus",
    "Intelligence": 85,
    "Power": 55,
    "Defense": 25,
    "Mobility": 60,
    "Health": 25,
    "Stealth": 100,
    "Image": 1,
    "Id": "octopus"
  },
  {
    "Name": "Albatross",
    "Intelligence": 55,
    "Power": 60,
    "Defense": 35,
    "Mobility": 100,
    "Health": 60,
    "Stealth": 30,
    "Image": 1,
    "Id": "albatross"
  },
  {
    "Name": "Pangolin",
    "Intelligence": 35,
    "Power": 75,
    "Defense": 100,
    "Mobility": 50,
    "Health": 45,
    "Stealth": 30,
    "Image": 1,
    "Id": "pangolin"
  },
  {
    "Name": "Dolphin",
    "Intelligence": 95,
    "Power": 25,
    "Defense": 30,
    "Mobility": 90,
    "Health": 60,
    "Stealth": 30,
    "Image": 1,
    "Id": "dolphin"
  },
  {
    "Name": "Owl",
    "Intelligence": 60,
    "Power": 42,
    "Defense": 39,
    "Mobility": 72,
    "Health": 38,
    "Stealth": 75,
    "Image": 1,
    "Id": "owl"
  },
  {
    "Name": "Rabbit",
    "Intelligence": 40,
    "Power": 45,
    "Defense": 50,
    "Mobility": 85,
    "Health": 45,
    "Stealth": 60,
    "Image": 1,
    "Id": "rabbit"
  },
  {
    "Name": "Seal",
    "Intelligence": 60,
    "Power": 45,
    "Defense": 60,
    "Mobility": 50,
    "Health": 70,
    "Stealth": 40,
    "Image": 1,
    "Id": "seal"
  },
  {
    "Name": "Horse",
    "Intelligence": 60,
    "Power": 65,
    "Defense": 50,
    "Mobility": 90,
    "Health": 30,
    "Stealth": 30,
    "Image": 1,
    "Id": "horse"
  },
  {
    "Name": "Shrew",
    "Intelligence": 20,
    "Power": 58,
    "Defense": 40,
    "Mobility": 85,
    "Health": 32,
    "Stealth": 88,
    "Image": 1,
    "Id": "shrew"
  },
  {
    "Name": "Seriema",
    "Intelligence": 80,
    "Power": 60,
    "Defense": 30,
    "Mobility": 60,
    "Health": 40,
    "Stealth": 50,
    "Image": 1,
    "Id": "seriema"
  },
  {
    "Name": "Pufferfish",
    "Intelligence": 40,
    "Power": 70,
    "Defense": 90,
    "Mobility": 35,
    "Health": 50,
    "Stealth": 30,
    "Image": 1,
    "Id": "pufferfish"
  },
  {
    "Name": "Ostrich",
    "Intelligence": 35,
    "Power": 75,
    "Defense": 55,
    "Mobility": 75,
    "Health": 60,
    "Stealth": 15,
    "Image": 1,
    "Id": "ostrich"
  },
  {
    "Name": "Shark",
    "Intelligence": 30,
    "Power": 80,
    "Defense": 50,
    "Mobility": 60,
    "Health": 50,
    "Stealth": 40,
    "Image": 1,
    "Id": "shark"
  },
  {
    "Name": "Echidna",
    "Intelligence": 20,
    "Power": 50,
    "Defense": 75,
    "Mobility": 60,
    "Health": 40,
    "Stealth": 65,
    "Image": 1,
    "Id": "echidna"
  },
  {
    "Name": "Deer",
    "Intelligence": 45,
    "Power": 50,
    "Defense": 40,
    "Mobility": 75,
    "Health": 50,
    "Stealth": 50,
    "Image": 1,
    "Id": "deer"
  },
  {
    "Name": "Coelacanth",
    "Intelligence": 10,
    "Power": 60,
    "Defense": 90,
    "Mobility": 15,
    "Health": 60,
    "Stealth": 70,
    "Image": 1,
    "Id": "coelacanth"
  },
  {
    "Name": "Squid",
    "Intelligence": 50,
    "Power": 78,
    "Defense": 10,
    "Mobility": 95,
    "Health": 20,
    "Stealth": 50,
    "Image": 1,
    "Id": "squid"
  },
  {
    "Name": "Armadillo",
    "Intelligence": 30,
    "Power": 10,
    "Defense": 100,
    "Mobility": 50,
    "Health": 50,
    "Stealth": 60,
    "Image": 1,
    "Id": "armadillo"
  },
  {
    "Name": "Emu",
    "Intelligence": 35,
    "Power": 50,
    "Defense": 45,
    "Mobility": 70,
    "Health": 60,
    "Stealth": 35,
    "Image": 1,
    "Id": "emu"
  },
  {
    "Name": "Parrot",
    "Intelligence": 95,
    "Power": 40,
    "Defense": 30,
    "Mobility": 70,
    "Health": 50,
    "Stealth": 10,
    "Image": 1,
    "Id": "parrot"
  },
  {
    "Name": "Hedgehog",
    "Intelligence": 30,
    "Power": 20,
    "Defense": 85,
    "Mobility": 60,
    "Health": 30,
    "Stealth": 70,
    "Image": 1,
    "Id": "hedgehog"
  },
  {
    "Name": "Tuatara",
    "Intelligence": 35,
    "Power": 70,
    "Defense": 55,
    "Mobility": 40,
    "Health": 45,
    "Stealth": 45,
    "Image": 1,
    "Id": "tuatara"
  },
  {
    "Name": "Platypus",
    "Intelligence": 20,
    "Power": 60,
    "Defense": 60,
    "Mobility": 60,
    "Health": 50,
    "Stealth": 35,
    "Image": 1,
    "Id": "platypus"
  },
  {
    "Name": "Box Jellyfish",
    "Intelligence": 5,
    "Power": 100,
    "Defense": 50,
    "Mobility": 20,
    "Health": 40,
    "Stealth": 70,
    "Image": 1,
    "Id": "box_jellyfish"
  },
  {
    "Name": "Snake",
    "Intelligence": 20,
    "Power": 50,
    "Defense": 30,
    "Mobility": 80,
    "Health": 20,
    "Stealth": 80,
    "Image": 1,
    "Id": "snake"
  },
  {
    "Name": "Heron",
    "Intelligence": 60,
    "Power": 50,
    "Defense": 40,
    "Mobility": 50,
    "Health": 30,
    "Stealth": 50,
    "Image": 1,
    "Id": "heron"
  },
  {
    "Name": "Aardvark",
    "Intelligence": 60,
    "Power": 55,
    "Defense": 40,
    "Mobility": 35,
    "Health": 35,
    "Stealth": 45,
    "Image": 1,
    "Id": "aardvark"
  },
  {
    "Name": "Tortoise",
    "Intelligence": 5,
    "Power": 35,
    "Defense": 95,
    "Mobility": 5,
    "Health": 90,
    "Stealth": 35,
    "Image": 1,
    "Id": "tortoise"
  },
  {
    "Name": "Toucan",
    "Intelligence": 50,
    "Power": 75,
    "Defense": 25,
    "Mobility": 65,
    "Health": 40,
    "Stealth": 10,
    "Image": 1,
    "Id": "toucan"
  },
  {
    "Name": "Kangaroo",
    "Intelligence": 20,
    "Power": 52,
    "Defense": 40,
    "Mobility": 80,
    "Health": 52,
    "Stealth": 20,
    "Image": 1,
    "Id": "kangaroo"
  },
  {
    "Name": "Rodent",
    "Intelligence": 80,
    "Power": 17,
    "Defense": 21,
    "Mobility": 59,
    "Health": 20,
    "Stealth": 66,
    "Image": 1,
    "Id": "rodent"
  },
  {
    "Name": "Pigeon",
    "Intelligence": 60,
    "Power": 20,
    "Defense": 35,
    "Mobility": 75,
    "Health": 30,
    "Stealth": 40,
    "Image": 1,
    "Id": "pigeon"
  },
  {
    "Name": "Catfish",
    "Intelligence": 10,
    "Power": 45,
    "Defense": 65,
    "Mobility": 40,
    "Health": 50,
    "Stealth": 45,
    "Image": 1,
    "Id": "catfish"
  },
  {
    "Name": "Turtle",
    "Intelligence": 10,
    "Power": 50,
    "Defense": 85,
    "Mobility": 10,
    "Health": 50,
    "Stealth": 45,
    "Image": 1,
    "Id": "turtle"
  },
  {
    "Name": "Manatee",
    "Intelligence": 50,
    "Power": 40,
    "Defense": 30,
    "Mobility": 50,
    "Health": 60,
    "Stealth": 15,
    "Image": 1,
    "Id": "manatee"
  },
  {
    "Name": "Anemone",
    "Intelligence": 5,
    "Power": 95,
    "Defense": 95,
    "Mobility": 0,
    "Health": 25,
    "Stealth": 25,
    "Image": 1,
    "Id": "anemone"
  },
  {
    "Name": "Flamingo",
    "Intelligence": 60,
    "Power": 15,
    "Defense": 40,
    "Mobility": 70,
    "Health": 45,
    "Stealth": 10,
    "Image": 1,
    "Id": "flamingo"
  },
  {
    "Name": "Anglerfish",
    "Intelligence": 20,
    "Power": 80,
    "Defense": 40,
    "Mobility": 40,
    "Health": 50,
    "Stealth": 0,
    "Image": 1,
    "Id": "anglerfish"
  },
  {
    "Name": "Kiwi",
    "Intelligence": 50,
    "Power": 15,
    "Defense": 30,
    "Mobility": 60,
    "Health": 25,
    "Stealth": 50,
    "Image": 1,
    "Id": "kiwi"
  },
  {
    "Name": "Hoatzin",
    "Intelligence": 60,
    "Power": 35,
    "Defense": 25,
    "Mobility": 65,
    "Health": 30,
    "Stealth": 15,
    "Image": 1,
    "Id": "hoatzin"
  },
  {
    "Name": "Frog",
    "Intelligence": 20,
    "Power": 15,
    "Defense": 10,
    "Mobility": 80,
    "Health": 23,
    "Stealth": 79,
    "Image": 1,
    "Id": "frog"
  },
  {
    "Name": "Tinamou",
    "Intelligence": 55,
    "Power": 20,
    "Defense": 30,
    "Mobility": 60,
    "Health": 25,
    "Stealth": 35,
    "Image": 1,
    "Id": "tinamou"
  },
  {
    "Name": "Pelican",
    "Intelligence": 50,
    "Power": 40,
    "Defense": 25,
    "Mobility": 45,
    "Health": 50,
    "Stealth": 15,
    "Image": 1,
    "Id": "pelican"
  },
  {
    "Name": "Crab",
    "Intelligence": 15,
    "Power": 55,
    "Defense": 75,
    "Mobility": 25,
    "Health": 40,
    "Stealth": 10,
    "Image": 1,
    "Id": "crab"
  },
  {
    "Name": "Bivalves",
    "Intelligence": 5,
    "Power": 7,
    "Defense": 100,
    "Mobility": 15,
    "Health": 45,
    "Stealth": 47,
    "Image": 1,
    "Id": "bivalves"
  },
  {
    "Name": "Toad",
    "Intelligence": 20,
    "Power": 10,
    "Defense": 32,
    "Mobility": 55,
    "Health": 32,
    "Stealth": 65,
    "Image": 1,
    "Id": "toad"
  },
  {
    "Name": "Lamprey",
    "Intelligence": 10,
    "Power": 70,
    "Defense": 20,
    "Mobility": 60,
    "Health": 10,
    "Stealth": 40,
    "Image": 1,
    "Id": "lamprey"
  },
  {
    "Name": "Lizard",
    "Intelligence": 30,
    "Power": 30,
    "Defense": 40,
    "Mobility": 50,
    "Health": 30,
    "Stealth": 25,
    "Image": 1,
    "Id": "lizard"
  },
  {
    "Name": "Flying fish",
    "Intelligence": 19,
    "Power": 19,
    "Defense": 22,
    "Mobility": 85,
    "Health": 10,
    "Stealth": 48,
    "Image": 1,
    "Id": "flying_fish"
  },
  {
    "Name": "Sloth",
    "Intelligence": 30,
    "Power": 10,
    "Defense": 40,
    "Mobility": 5,
    "Health": 50,
    "Stealth": 60,
    "Image": 1,
    "Id": "sloth"
  },
  {
    "Name": "Snail",
    "Intelligence": 10,
    "Power": 5,
    "Defense": 95,
    "Mobility": 3,
    "Health": 45,
    "Stealth": 30,
    "Image": 1,
    "Id": "snail"
  },
  {
    "Name": "Hagfish",
    "Intelligence": 40,
    "Power": 10,
    "Defense": 20,
    "Mobility": 50,
    "Health": 10,
    "Stealth": 50,
    "Image": 1,
    "Id": "hagfish"
  },
  {
    "Name": "Hummingbird",
    "Intelligence": 40,
    "Power": 5,
    "Defense": 5,
    "Mobility": 100,
    "Health": 10,
    "Stealth": 10,
    "Image": 1,
    "Id": "hummingbird"
  },
  {
    "Name": "Spider",
    "Intelligence": 10,
    "Power": 45,
    "Defense": 50,
    "Mobility": 5,
    "Health": 5,
    "Stealth": 50,
    "Image": 1,
    "Id": "spider"
  },
  {
    "Name": "Jellyfish",
    "Intelligence": 5,
    "Power": 50,
    "Defense": 40,
    "Mobility": 5,
    "Health": 15,
    "Stealth": 50,
    "Image": 1,
    "Id": "jellyfish"
  },
  {
    "Name": "Starfish",
    "Intelligence": 3,
    "Power": 22,
    "Defense": 32,
    "Mobility": 10,
    "Health": 62,
    "Stealth": 17,
    "Image": 1,
    "Id": "starfish"
  },
  {
    "Name": "Bryozoa",
    "Intelligence": 9,
    "Power": 14,
    "Defense": 15,
    "Mobility": 1,
    "Health": 40,
    "Stealth": 60,
    "Image": 1,
    "Id": "bryozoa"
  },
  {
    "Name": "Copepod",
    "Intelligence": 15,
    "Power": 5,
    "Defense": 10,
    "Mobility": 20,
    "Health": 1,
    "Stealth": 80,
    "Image": 1,
    "Id": "copepod"
  },
  {
    "Name": "Brittle star",
    "Intelligence": 5,
    "Power": 15,
    "Defense": 15,
    "Mobility": 35,
    "Health": 25,
    "Stealth": 30,
    "Image": 1,
    "Id": "brittle_star"
  },
  {
    "Name": "Xenacoelomorpha",
    "Intelligence": 6,
    "Power": 10,
    "Defense": 0,
    "Mobility": 20,
    "Health": 20,
    "Stealth": 40,
    "Image": 1,
    "Id": "xenacoelomorpha"
  },
  {
    "Name": "Entoprocta",
    "Intelligence": 7,
    "Power": 10,
    "Defense": 10,
    "Mobility": 1,
    "Health": 25,
    "Stealth": 40,
    "Image": 1,
    "Id": "entoprocta"
  },
  {
    "Name": "Sponge",
    "Intelligence": 0,
    "Power": 0,
    "Defense": 50,
    "Mobility": 0,
    "Health": 25,
    "Stealth": 0,
    "Image": 1,
    "Id": "sponge"
  },
  {
    "Name": "Sea lily",
    "Intelligence": 0,
    "Power": 10,
    "Defense": 45,
    "Mobility": 3,
    "Health": 10,
    "Stealth": 0,
    "Image": 1,
    "Id": "sea_lily"
  },
  {
    "Name": "Human",
    "Intelligence": 100,
    "Power": 50,
    "Defense": 1,
    "Mobility": 70,
    "Health": 40,
    "Stealth": 1,
    "Image": 1,
    "Id": "human"
  }
]